//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyMapWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_familyRelation
    {
        public int familyRelationId { get; set; }
        public int familyNo { get; set; }
        public int familyMemId { get; set; }
    
        public virtual tbl_Family tbl_Family { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
