//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyMap.FamilyMapServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FamilyMapServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFamilyMember", ReplyAction="http://tempuri.org/IService1/GetAllFamilyMemberResponse")]
        FamilyMapWCFService.WCP_Family[] GetAllFamilyMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFamilyMember", ReplyAction="http://tempuri.org/IService1/GetAllFamilyMemberResponse")]
        System.Threading.Tasks.Task<FamilyMapWCFService.WCP_Family[]> GetAllFamilyMemberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FamilyMap.FamilyMapServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FamilyMap.FamilyMapServiceReference.IService1>, FamilyMap.FamilyMapServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FamilyMapWCFService.WCP_Family[] GetAllFamilyMember() {
            return base.Channel.GetAllFamilyMember();
        }
        
        public System.Threading.Tasks.Task<FamilyMapWCFService.WCP_Family[]> GetAllFamilyMemberAsync() {
            return base.Channel.GetAllFamilyMemberAsync();
        }
    }
}
